language: node_js
node_js:
  - "8"

# Displays time before each script
before_script:
  - date

# Displays time after each script
after_script:
  - date

script:
 - cd website/
 - npm install npm@latest -g
 - npm install
 - npm run lint


