language: node_js
node_js:
  - "8"

stages:
  - static_analysis
  - test

# Displays time before each script
before_script:
  - date

# Displays time after each script
after_script:
  - date

jobs:
   include:
    - stage: static_analysis
      script:
       - cd website/
       - npm install npm@latest -g
       - npm install
       - npm run lint
    - stage: static_analysis
      script:
       - cd website/
       - npm install npm@latest -g
       - npm install
       - npm test
       - npm run coveralls
