language: node_js
node_js:
  - "6"


# Displays time before each script
before_script:
  - date

# Displays time after each script
after_script:
  - date

# Stages
stages:
  - static-analyis

nodejs-static-analysis:
  stage: static-analysis

  before_script:
    - cd website/

  script:
    - npm install npm@latest -g
    - npm install
    - npm run lint


